spring.application.name=demo

# R2DBC (Reaktiv databasåtkomst)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/message_db
spring.r2dbc.username=postgres
spring.r2dbc.password=

# Flyway (JDBC för migrationer)
spring.flyway.url=jdbc:postgresql://localhost:5432/message_db
spring.flyway.user=postgres
spring.flyway.password=
spring.flyway.locations=classpath:db/migration